# Generated by Django 5.2 on 2025-04-25 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('spam', 'Spam Detection'), ('virus', 'File/Malware Scan'), ('url', 'URL Analysis'), ('ip', 'IP Address Analysis'), ('combined', 'Combined Security Check')], max_length=20)),
                ('content', models.TextField(blank=True, help_text='Message, URL, or IP address', null=True)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash', max_length=64, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_data', models.JSONField(blank=True, help_text='API scan results', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpamClassificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('feature_extraction_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityThreat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('threat_type', models.CharField(choices=[('spam', 'Spam'), ('phishing', 'Phishing'), ('malware', 'Malware'), ('virus', 'Virus'), ('ransomware', 'Ransomware'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('detection_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='security_analyzer.securityscan')),
            ],
            options={
                'ordering': ['-detection_timestamp'],
            },
        ),
    ]
